import pandas as pd
import logging
import os
from pydantic import ValidationError
from scraper.crawler import fetch_page_html
from scraper.parser import FoodParser
from pipeline.cleaner import clean_rating
from pipeline.storage import FoodStorage
from pipeline.schema import RestaurantSchema
from pipeline.notifier import TelegramNotifier

log_directory = "logs"
if not os.path.exists(log_directory):
    os.makedirs(log_directory)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(f"{log_directory}/scraper_pipeline.log", encoding='utf-8'),
        logging.StreamHandler()
    ]
)

def run_pipeline():
    TARGET_URL = "https://www.yellowpages.com/search?search_terms=restaurants&geo_location=Surabaya"
    storage = FoodStorage()
    notifier = TelegramNotifier()
    
    logging.info(f"Starting Extraction Pipeline targeting: {TARGET_URL}")

    # 1. Extract
    html = fetch_page_html(TARGET_URL)
    if not html:
        error_msg = "[ERROR] Pipeline Gagal: Gagal mengambil HTML dari target."
        logging.error(error_msg)
        notifier.send_message(error_msg)
        return

    # 2. Transform - Parse HTML
    raw_data = FoodParser.parse_restaurant_list(html)
    if not raw_data:
        warn_msg = "[WARNING] Pipeline Peringatan: Tidak ada data yang berhasil diekstrak."
        logging.warning(warn_msg)
        notifier.send_message(warn_msg)
        return

    # 3. Transform - Clean & Validate Data 
    logging.info("Starting data cleaning and validation process.")
    valid_data = []
    
    for item in raw_data:
        cleaned_rating = clean_rating(item.get('rating', '0'))
        item['rating'] = cleaned_rating
        
        # Validasi skema dengan Pydantic
        try:
            validated_item = RestaurantSchema(**item)
            valid_data.append(validated_item.model_dump())
        except ValidationError as e:
            logging.warning(f"Data validation failed for item {item.get('name')}: {e.errors()[0]['msg']}")

    if not valid_data:
        error_msg = "[ERROR] Pipeline Gagal: Semua data gagal divalidasi. Tidak ada yang disimpan."
        logging.error(error_msg)
        notifier.send_message(error_msg)
        return

    # Konversi data yang sudah tervalidasi ke DataFrame
    df = pd.DataFrame(valid_data)
    
    # 4. Load
    logging.info("Attempting to load validated data into database.")
    storage.save_restaurants(df)
    
    # 5. Report (Notifikasi Telegram dengan Business Insights)
    valid_df = df[df['rating'] > 0]
    
    if not valid_df.empty:
        avg_rating = valid_df['rating'].mean()
        top_tier_count = len(valid_df[valid_df['rating'] >= 4.5])
        low_tier_count = len(valid_df[valid_df['rating'] < 3.0])
        
        # Mengambil Top 3 restoran berdasarkan rating tertinggi
        top_3 = valid_df.nlargest(3, 'rating')
        top_3_text = "\n".join([f"  - {row['name']} (Rating: {row['rating']})" for _, row in top_3.iterrows()])
    else:
        avg_rating = 0.0
        top_tier_count = 0
        low_tier_count = 0
        top_3_text = "  - N/A"

    success_msg = (
        "<b>[SYSTEM ALERT] PIPELINE EXECUTION SUCCESS</b>\n\n"
        "<b>EXECUTION SUMMARY</b>\n"
        f"Target URL: YellowPages\n"
        f"Extracted Data: {len(raw_data)} records\n"
        f"Passed Validation: {len(df)} records\n\n"
        "<b>DATA INSIGHTS</b>\n"
        f"Average Rating: {avg_rating:.2f} / 5.0\n"
        f"Elite Tier (4.5+): {top_tier_count} restaurants\n"
        f"Low Tier (Under 3.0): {low_tier_count} restaurants\n\n"
        "<b>TOP 3 RESTAURANTS:</b>\n"
        f"{top_3_text}\n\n"
        "<i>Generated by Ruphas Assistant Bot</i>"
    )
    
    logging.info(f"Pipeline execution completed. Valid records saved: {len(df)} / {len(raw_data)}")
    notifier.send_message(success_msg)

if __name__ == "__main__":
    run_pipeline()